apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game-2048-container
          image: charanreddy12/game-2048:latest  
          ports:
            - containerPort: 80
