apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  labels:
    app: game
spec:
  type: NodePort
  selector:
    app: game
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      nodePort: 31000
